export type TeamStats = {
  id: number;
  season: string;
  team_one: number;
  games_played?: number; // Optional since it's not marked as `notNullable`
  wins?: number;
  mins: number;
  fg3: number;
  fga3: number;
  fg2: number;
  fga2: number;
  fga: number;
  ft: number;
  fta: number;
  fg?: number;
  fg_percent?: number;
  "3pt_percent"?: number;
  "2pt_percent"?: number;
  efg_percent?: number;
  ft_percent?: number;
  oreb: number;
  dreb: number;
  reb: number;
  pf: number;
  assist: number;
  turn: number;
  block: number;
  steal: number;
  points: number;
  possessions?: number;
  offrtg?: number;
  defrtg?: number;
  offrtg_adj?: number;
  defrtg_adj?: number;
  pace?: number;
};

export type PlayerStats = {
  id: number;
  season: string;
  team_id: number;
  player_id: number;
  games_played: number;
  mins: number;
  fg3: number;
  fga3: number;
  fg2: number;
  fga2: number;
  fga: number;
  ft: number;
  fta: number;
  fg: number;
  fg_percent: number;
  "3pt_percent": number;
  "2pt_percent": number;
  efg_percent: number;
  ft_percent: number;
  oreb: number;
  dreb: number;
  reb: number;
  pf: number;
  assist: number;
  turn: number;
  block: number;
  steal: number;
  points: number;
  possessions: number | null;
  player_name: string;
  tsa: number;
  pts_tsTsa: number;
  pts_adj: number;
  poss: number;
  threshPts: number;
  adj_pts_p100: number;
  fga_p100: number;
  fta_p100: number;
  fg3_p100: number;
  ast_p100: number;
  to_p100: number;
  orb_p100: number;
  drb_p100: number;
  trb_p100: number;
  stl_p100: number;
  blk_p100: number;
  pf_p100: number;
  percent_min: number;
  percent_treb: number;
  percent_stl: number;
  percent_pf: number;
  percent_ast: number;
  percent_blk: number;
  percent_threshPts: number;
  position: number;
};

export type BPMCoefficientsType = {
  adjPt: number;
  fga: number;
  fta: number;
  threePtFg: number;
  ast: number;
  to: number;
  orb: number;
  drb: number;
  trb: number;
  stl: number;
  blk: number;
  pf: number;
};

export type TeamShotDistribution = {
  threes: number;
  twos: number;
};