"""new pbp table

Revision ID: 1b0fbd03f022
Revises: d968d9c3edae
Create Date: 2025-02-24 19:07:44.647977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0fbd03f022'
down_revision = 'd968d9c3edae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_by_play',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('clock_time', sa.Integer(), nullable=True),
    sa.Column('time_remaining', sa.Integer(), nullable=True),
    sa.Column('utc_time', sa.DateTime(), nullable=True),
    sa.Column('offense_team', sa.String(), nullable=True),
    sa.Column('defense_team', sa.String(), nullable=True),
    sa.Column('is_home_offense', sa.Boolean(), nullable=True),
    sa.Column('offense_player', sa.String(), nullable=True),
    sa.Column('offense_player_id', sa.String(), nullable=True),
    sa.Column('result_player', sa.String(), nullable=True),
    sa.Column('result_player_id', sa.String(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('play_result', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('play_number', sa.Integer(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('after_timeout', sa.Boolean(), nullable=True),
    sa.Column('shot_quality', sa.REAL(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('run_team', sa.String(), nullable=True),
    sa.Column('run_points', sa.Integer(), nullable=True),
    sa.Column('home_run', sa.Integer(), nullable=True),
    sa.Column('away_run', sa.Integer(), nullable=True),
    sa.Column('score_margin', sa.Integer(), nullable=True),
    sa.Column('score_margin_percent', sa.REAL(), nullable=True),
    sa.Column('possession_number', sa.Integer(), nullable=True),
    sa.Column('seconds_remaining', sa.Integer(), nullable=True),
    sa.Column('game_percent_complete', sa.REAL(), nullable=True),
    sa.Column('points_last_minute', sa.Integer(), nullable=True),
    sa.Column('possessions_last_minute', sa.Integer(), nullable=True),
    sa.Column('lead_changes', sa.Integer(), nullable=True),
    sa.Column('largest_lead', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Boolean(), nullable=True),
    sa.Column('double_bonus', sa.Boolean(), nullable=True),
    sa.Column('timeouts_remaining_home', sa.Integer(), nullable=True),
    sa.Column('timeouts_remaining_away', sa.Integer(), nullable=True),
    sa.Column('previous_play_type', sa.String(), nullable=True),
    sa.Column('time_since_last_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('play_by_play_game_id_idx', 'play_by_play', ['game_id'], unique=False)
    op.create_index('play_by_play_offense_player_idx', 'play_by_play', ['offense_player'], unique=False)
    op.create_index('play_by_play_offense_team_idx', 'play_by_play', ['offense_team'], unique=False)
    op.drop_index('play_by_play_game_id_play_actor_team_play_actor_player_index', table_name='play_by_play_old')
    op.create_index('pbp_old_game_actor_idx', 'play_by_play_old', ['game_id', 'play_actor_team', 'play_actor_player'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pbp_old_game_actor_idx', table_name='play_by_play_old')
    op.create_index('play_by_play_game_id_play_actor_team_play_actor_player_index', 'play_by_play_old', ['game_id', 'play_actor_team', 'play_actor_player'], unique=False)
    op.drop_index('play_by_play_offense_team_idx', table_name='play_by_play')
    op.drop_index('play_by_play_offense_player_idx', table_name='play_by_play')
    op.drop_index('play_by_play_game_id_idx', table_name='play_by_play')
    op.drop_table('play_by_play')
    # ### end Alembic commands ### 