"""remove jersey number

Revision ID: 3f68c89bfeaf
Revises: e71461210ee1
Create Date: 2025-02-09 13:10:22.023530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f68c89bfeaf'
down_revision = 'e71461210ee1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'jersey_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('jersey_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 