"""add jersey number to players

Revision ID: e71461210ee1
Revises: 
Create Date: 2025-02-09 13:07:22.727638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e71461210ee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knex_migrations')
    op.drop_table('test_table')
    op.drop_table('knex_migrations_lock')
    op.add_column('players', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.alter_column('team_game_stats', 'possessions',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'offrtg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'defrtg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'pace',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'possessions',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'offrtg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'defrtg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'offrtg_adj',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'defrtg_adj',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'pace',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_season_stats', 'pace',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'defrtg_adj',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'offrtg_adj',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'defrtg',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'offrtg',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'possessions',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'pace',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'defrtg',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'offrtg',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('team_game_stats', 'possessions',
               existing_type=sa.REAL(precision=53),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('players', 'jersey_number')
    op.create_table('knex_migrations_lock',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_locked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name='knex_migrations_lock_pkey')
    )
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.create_table('knex_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('migration_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='knex_migrations_pkey')
    )
    # ### end Alembic commands ### 