# Auto-generated from database - do not edit directly

team_ids = {
    "Waterloo": 1,
    "Acadia": 2,
    "Cape Breton": 3,
    "Dalhousie": 4,
    "Memorial": 5,
    "StFX": 6,
    "Saint Marys": 7,
    "UNB": 8,
    "UPEI": 9,
    "Alberta": 10,
    "Brandon": 11,
    "Calgary": 12,
    "Lethbridge": 13,
    "MacEwan": 14,
    "Manitoba": 15,
    "Mount Royal": 16,
    "Regina": 17,
    "Saskatchewan": 18,
    "Thompson Rivers": 19,
    "Trinity Western": 20,
    "UBC": 21,
    "UBC Okanagan": 22,
    "UFV": 23,
    "UNBC": 24,
    "Victoria": 25,
    "Winnipeg": 26,
    "Algoma": 27,
    "Brock": 28,
    "Carleton": 29,
    "Guelph": 30,
    "Lakehead": 31,
    "Laurentian": 32,
    "McMaster": 33,
    "Nipissing": 34,
    "Ontario Tech": 35,
    "Ottawa": 36,
    "Queens": 37,
    "TMUnow": 38,
    "Toronto": 39,
    "Western": 40,
    "WLUteam": 41,
    "Windsor": 42,
    "York": 43,
    "Bishops": 44,
    "Concordia": 45,
    "Laval": 46,
    "McGill": 47,
    "UQAM": 48,
}
